
project:
  type: website

website:
  title: "Antonio Rojas Castro"
  site-url: https://arojascastro.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects/index.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/arojascastro
  page-footer:
    left: "2025 © Antonio Rojas Castro"
    right:
      - icon: envelope
        href: mailto:antonio.rojas.castro@fu-berlin.de
        aria-label: email
format:
  html:
    theme: flatly
    toc: true
    smooth-scroll: true
    code-copy: true
  
execute:
  freeze: auto
