
---
title: "About"
---

Hello!

I am a Digital Humanities researcher with a **PhD in Humanities** from Universitat Pompeu Fabra (Barcelona), where I specialized in digital scholarly editing. My dissertation (2011–2015) focused on Luis de Góngora’s *Soledades*, for which I manually collated twenty witnesses and published a critical edition using [Edition Visualization Technology (EVT)](http://soledades.uni-koeln.de/#/critical?d=doc_1&e=critical).

Since then, I’ve contributed to a range of interdisciplinary projects across Europe. At the **Cologne Center for eHumanities** (2016–2019), I helped design and implement the bibliographic data model for [*HallerNet*](https://hallernet.org/), a digital platform dedicated to the Swiss Enlightenment. From 2019 to 2025, I worked at the **Berlin-Brandenburg Academy of Sciences and Humanities**, developing the multilingual [*Dossier Digital: Alexander von Humboldt and Cuba*](https://dossierdigital.ohc.cu/exist/apps/ProHD/start.html) as part of the *Proyecto Humboldt Digital*.

Currently, I am a **Research Associate** at the **University of Tübingen**, where I explore recurring patterns in Calderón de la Barca’s drama through computational methods. I also collaborate with the **Freie Universität Berlin** on the [DraCor](https://dracor.org/) project, contributing to its technical development, training materials, and open science integration.

In parallel, I taught from **2020 to 2025** as a **Part-Time Lecturer** in the Digital Humanities master’s program at the **Universidad Internacional de La Rioja (UNIR)**. I offered a course on [digital scholarly editing](https://static.unir.net/guias_espana/guias_nuevas/hudi03_edicion_digital_textos.htm) and supervised several MA theses.

I’m passionate about community-driven scholarship and open knowledge. Over the past decade, I’ve volunteered with initiatives such as:

- [text+](https://text-plus.org/) (2025–Present)  
- [Asociación de Humanidades Digitales Hispánicas (HDH)](https://humanidadesdigitaleshispanicas.es/inicio/) (2021–2023)  
- [The Programming Historian](https://programminghistorian.org/) (2016–2020)  
- [European Association for Digital Humanities (EADH)](https://eadh.org/) (2015–2018)  

Outside of work, I enjoy sports, drawing, reading, and discovering new places.


