
---
title: "Home"
page-layout: article
---

# Dr. Antonio Rojas Castro

I am a Digital Humanities Research Associate at the **Freie Universität Berlin** and the **University of Tübingen**. I specialize in digital editions and computational literary studies. My current project focuses on network analysis and the role of character typologies such as the _gracioso_ in Golden Age theater in Spain, using computational methods and corpus analysis.

I am also a Part-Time Lecturer at **Universidad Internacional de La Rioja** (MA in Digital Humanities). I am currently teaching a course on digital scholarly editing and supervising MA dissertations on Digital Humanities.

I have voluntereed in several organizations: the European Association for Digital Humanities (2015-2018), The Programming Historian en español (2016-2020), and the Asociación de Humanidades Digitales Hispánicas (2021-2023).

You can found more information about my work at:

- ORCID: <https://orcid.org/0000-0002-8916-4997>  
- GitHub: <https://github.com/arojascastro>  
- Zotero: <https://www.zotero.org/antoniorojascastro>


